version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-backend-clean-architecture-db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres:persistent
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:

networks:
  default:
    name: app-network